crypto:
  cert: conf/cert.pem
  key: conf/key.pem
server:
  host: 192.168.38.66
  https: true
  port: 8888
users:
- name: admin
  password: caldera
proxy:
  default:
    cert: ''
    http: ''
    https: ''
